apiVersion: v1
kind: Service
metadata: 
  name: python-app
spec:
  type: NodePort
  selector: 
    app: python
  ports:
  - name:
    protocol: TCP      
    port: 5000
    targetPort: 5000
    nodePort: 30001

